version: "3.9"

services:
  klipper3d:
    image: freakyd/klipper3d
    build: klipper3d/.
    container_name: klipper3d
    hostname: klipper3d
    restart: unless-stopped
    volumes:
      - ./configs:/opt/configs
      - ./gcodes:/opt/gcodes
      - klipper-env:/opt/klipper
      - /tmp/logs:/opt/logs
      - klipper-socket-api:/opt/socket-api
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    networks:
      - klipper

  moonraker:
    image: freakyd/moonraker
    build: moonraker/.
    container_name: moonraker
    hostname: moonraker
    depends_on:
      - klipper3d
    restart: unless-stopped
    volumes:
      - ./configs:/opt/configs
      - ./gcodes:/opt/gcodes
      - klipper-env:/opt/klipper
      - /tmp/logs:/opt/logs
      - moonraker-db:/opt/db
      - klipper-socket-api:/opt/socket-api
    ports:
      - 7125:7125
    networks:
      - klipper

  mainsail:
    image: ghcr.io/mainsail-crew/mainsail:latest
    container_name: mainsail
    hostname: mainsail
    depends_on:
      - moonraker
    restart: unless-stopped
    volumes:
      - ./mainsail/config.json:/usr/share/nginx/html/config.json
    ports:
      - 80:80
    networks:
      - klipper

  mjpgstreamer:
    image: freakyd/mjpgstreamer
    build: mjpgstreamer/.
    container_name: mjpgstreamer
    hostname: mjpgstreamer
    restart: unless-stopped
    devices:
      - /dev/video0:/dev/video0
    environment:
      INPUTUVC: "-r 1280x720"
      V4L2CTRLS: "focus_automatic_continuous=0,focus_absolute=333"
    ports:
      - 8080:8080
    networks:
      - klipper

volumes:
  klipper-socket-api:
  moonraker-db:
  klipper-env:

networks:
  klipper:

