version: "3.9"

services:
  klipper:
    build: klipper/.
    container_name: klipper
    hostname: klipper
    restart: unless-stopped
    volumes:
      - ./configs:/opt/configs
      - klipper-env:/opt/klipper
      - ./logs:/opt/logs
      - klipper-socket-api:/opt/socket-api
    devices:
      - /dev/ttyACM0:/dev/ttyACM0
    networks:
      - klipper      

  moonraker:
    build: moonraker/.
    container_name: moonraker
    hostname: moonraker
    depends_on:
      - klipper
    restart: unless-stopped
    volumes:
      - ./configs:/opt/configs
      - klipper-env:/opt/klipper
      - ./logs:/opt/logs
      - moonraker-db:/opt/db
      - klipper-socket-api:/opt/socket-api
    ports:
      - 7125:7125
    networks:
      - klipper      

  mainsail:
    image: ghcr.io/mainsail-crew/mainsail:latest
    container_name: mainsail
    hostname: mainsail
    depends_on:
      - moonraker
    restart: unless-stopped
    volumes:
      - ./mainsail/config.json:/usr/share/nginx/html/config.json
    ports:
      - 80:80
    networks:
      - klipper

  mjpgstreamer:
    build: mjpgstreamer/.
    container_name: mjpgstreamer
    hostname: mjpgstreamer
    restart: unless-stopped
    volumes:
      - /dev/video0:/dev/video0
    environment:
      - RESOLUTION="1280x720"    
    ports:
      - 8081:8080
    networks:
      - klipper

volumes:
  klipper-socket-api:
  moonraker-db:
  klipper-env: 

networks:
  klipper: 
    
